spring.application.name=lib-web
#oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=ADM_55230931
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#JPA
# use self-make Oracle 11g
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none

#Hibernate naming strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
server.port=8081
server.address=0.0.0.0
# QQ??SMTP??
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=2017934282@qq.com
spring.mail.password=xqgdnuzhpacgdccf
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8
# ??????
spring.task.scheduling.enabled=true

# ?????????
spring.task.scheduling.pool.size=5
spring.task.scheduling.thread-name-prefix=scheduled-task-
# QQ??SMTP??
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true